name: Build and deploy

# TODO production branch
on:
  push:
    branches:
      - production


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: |
          npm ci
          npm run-script build
          npm run-script test

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.PAGES_DEPLOY_KEY }}
          external_repository: fruktkartan/fruktkartan.github.io
          publish_branch: master
          publish_dir: ./dist
          allow_empty_commit: true
          user_name: 'fruktrobot'
          user_email: '<>'
